---
title: "Null_Data_Challenge"
author: "Roger Yuan"
date: "9/3/2019"
output: html_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Import Datasets
```{r}
library(readr)
# Roger
ride_ids <- read_csv("~/Desktop/Lyft Data Challenge/Lyft Data/ride_ids.csv")
driver_ids <- read_csv("~/Desktop/Lyft Data Challenge/Lyft Data/driver_ids.csv")
ride_timestamps <- read_csv("~/Desktop/Lyft Data Challenge/Lyft Data/ride_timestamps.csv")
```

```{r}
library(readr)
# Edwin
ride_ids <- read_csv("C:/Users/Edwin/Downloads/ride_ids.csv")
driver_ids <- read_csv("C:/Users/Edwin/Downloads/driver_ids.csv")
ride_timestamps <- read_csv("C:/Users/Edwin/Downloads/ride_timestamps.csv")
```

##Revenue for Each Driver
```{r}
library(tidyverse)
ride_ids$revenue <- round(1.75 + (2 + 0.22 * ride_ids$ride_duration/60 + 1.15 * 0.000621371 * ride_ids$ride_distance) * (1 + ride_ids$ride_prime_time/100), digits = 2)

ride_ids$revenue[ride_ids$revenue < 5] <- 5
ride_ids$revenue[ride_ids$revenue > 400] <- 400

ride_ids %>% 
  group_by(driver_id) %>% 
  summarise(total_rev = sum(revenue)) %>% 
  arrange(desc(total_rev))
```

# tag rides with time of day, sum up all prime time bonuses for drivers
```{r}
# switch timezone
attributes(ride_timestamps$timestamp)$tzone <- "America/Los_Angeles"

# morning rush hour 5-10
# evening rush hour 3-7
timeofday <- function(datetime) {
  num = as.numeric(strftime(datetime, format="%H"))
  if ((num < 5) | (num >= 19)) return("night")
  if ((5 <= num) & (num < 10)) return("morning rush")
  if ((10 <= num) & (num < 12)) return("morning")
  if ((12 <= num) & (num < 15)) return("afternoon")
  if ((15 <= num) & (num < 19)) return("evening rush")
  else return(NULL)
}

# assign time of day for ride based on accepted_at timestamp
acceptedat <- ride_timestamps[which(ride_timestamps$event == 'accepted_at'),]


# long function, has to run row by row
acceptedat$dayinfo <- apply(acceptedat, 1, function(x) {timeofday(x[3])})

# for (i in 1:(length(acceptedat$ride_id))) {
#   acceptedat$dayinfo[i] <- timeofday(acceptedat$timestamp[i])
# }

alldata <- left_join(ride_ids, acceptedat[c("ride_id", "dayinfo")], by="ride_id")

# find total prime time bonus for each driver
sumprime <- aggregate(alldata$ride_prime_time, by=list(driver_id=alldata$driver_id), FUN=sum)
colnames(sumprime) <- c("driver_id", "totalprimetime")

# join totalprimetime bonus with driver_id table
driver_ids <- inner_join(driver_ids, sumprime, by="driver_id")
```


##Driver's Lifetime
```{r}
rides <- 
  ride_timestamps %>% 
  group_by(ride_id) %>% 
  summarise(latest_time = max(timestamp))
ride_ids2 <- inner_join(x = ride_ids, y = rides, by = "ride_id")

driver_times <- 
  ride_ids2 %>% 
  group_by(driver_id) %>% 
  summarise(latest_time = max(latest_time))

driver_lifetime <- inner_join(driver_ids, driver_times, "driver_id")
driver_lifetime$life_time <- driver_lifetime$latest_time - driver_lifetime$driver_onboard_date

driver_lifetime %>% arrange(desc(life_time))
mean(driver_lifetime$life_time, na.rm = T)
```

##Time Between Rides
```{r}
Driver_timestamps <- left_join(x = ride_timestamps, y = ride_ids, by = "ride_id")
bruhh <- Driver_timestamps %>% 
  filter(event == "requested_at") %>% 
  arrange(timestamp) %>% 
  arrange(driver_id)

timediff <- function(time1, time2) {
  diff = difftime(time1, time2)
  if (units(diff) == "secs") {
    return(as.numeric(diff) / 60)
  }
  if (units(diff) == "hours") {
    return(as.numeric(diff) * 60)
  }
  return(as.numeric(diff))
}

bruhh2 <- bruhh %>% select(driver_id, timestamp)
bruhh2$difference = c(NA, round(diff(bruhh2$timestamp)/60))
bruhh2
```



##Big Inner Join
```{r}
all_rides <- inner_join(x = ride_ids, y = driver_ids, by = "driver_id")
all_rides <- inner_join(x = all_rides, y = ride_timestamps, by = c("ride_id"))

Driver_summary <- 
  all_rides %>% 
  group_by(driver_id) %>% 
  summarise(Total_Rev = sum(revenue), life_time = max(timestamp - driver_onboard_date), 
            Total_distance = sum(ride_distance), Total_duration = sum(ride_duration),
            Total_prime_time = sum(ride_prime_time))
Driver_summary$life_time <- as.numeric(Driver_summary$life_time)/24
Driver_summary
```


#investigate timestamps of outlier drivers
```{r}
# driver id and revenue
driver_rev <- ride_ids %>% 
  group_by(driver_id) %>% 
  summarise(total_rev = sum(revenue)) %>% 
  arrange(desc(total_rev))

ride_timestamps <- inner_join(ride_ids[,c('driver_id', 'ride_id')], ride_timestamps, by='ride_id')

timediff <- function(time1, time2) {
  diff = difftime(time1, time2)
  if (units(diff) == "secs") {
    return(as.numeric(diff) / 60)
  }
  if (units(diff) == "hours") {
    return(as.numeric(diff) * 60)
  }
  return(as.numeric(diff))
}

# subtract dropped off from requested time
ride_summary <- aggregate(ride_timestamps$timestamp, by=list(ride_id=ride_timestamps$ride_id), FUN=function(x)timediff(range(x)[2], range(x)[1]))
#only pickedup and droppedoff
temp2 <- ride_timestamps[which(ride_timestamps$event == 'picked_up_at' | ride_timestamps$event == 'dropped_off_at'),]
travel_times <- aggregate(temp2$timestamp, by=list(ride_id=temp2$ride_id), 
                          FUN=function(x) timediff(range(x)[2], range(x)[1]))

# get times with no revenue
ride_summary$norider <- (ride_summary$x - travel_times$x)
colnames(ride_summary)[2] <- 'totaltime'

#ride_summary$totaltime <- as.numeric(ride_summary$totaltime)
ride_summary <- inner_join(ride_ids[,c('driver_id', 'ride_id')], ride_summary, by='ride_id')
ride_summary$percentnorev <- ride_summary$norider / ride_summary$totaltime
```


```{r}
# driver ids with outlier revenue
driverid_out <- driver_rev$driver_id[which(driver_rev$total_rev %in% boxplot(driver_rev$total_rev)$out)]
ride_summary[which(ride_summary$driver_id %in% driverid_out),]
meannorev <- aggregate(ride_summary$percentnorev, by=list(driver_id=ride_summary$driver_id), FUN=mean)
# ride timestamps with outlier driver revenue
time_out <- ride_timestamps[which(ride_timestamps$driver_id %in% driver_out),]
```


##OLS Regression Analysis
```{r}
library(glmnet)
which(is.na(Driver_summary), arr.ind=TRUE)
Driver_summary[425, 3] <- median(Driver_summary[[3]], na.rm = T)

X <- model.matrix(Total_Rev ~., data = Driver_summary[,-1])[,-1]
Y <- Driver_summary$Total_Rev

#Creating 70% training, 30% testing data
set.seed(777)
train <- sample(1:nrow(X), round(0.7 * nrow(X)))
test <- (-train)
Y_test <- Y[test]

##OLS
driver_lm <- lm(Total_Rev ~ 0 + life_time + Total_distance + Total_duration
                + Total_prime_time, data = Driver_summary[,-1])
summary(driver_lm)

coef(driver_lm)
length(Y)

lassofit = glmnet(X, Y)
# we can see lasso will push a paramter value down to 0
as.matrix(t(coef(lassofit, s = 0.5))) 

```
